# Generated by Django 3.2.7 on 2021-09-08 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='login',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.login'),
            preserve_default=False,
        ),
    ]
